#!/bin/bash

curdir=`pwd`

if [ ! -e ${HOME}/.vpython/3/mkdocs/bin/python ]; then
    echo "Setting up mkdocs"
    curdir=`pwd`
    mkdir -p  ${HOME}/.vpython/3
    cd /Users/ashish/.vpython/3
    virtualenv mkdocs
    source /Users/ashish/.vpython/3/mkdocs/bin/activate
    pip install mkdocs
    pip install mkdocs-material
    pip install pymdown-extensions
    cd ${curdir}
    deactivate
fi

source /Users/ashish/.vpython/3/mkdocs/bin/activate

if [ ! -e ${curdir}/mkdocs.yml ];then
echo "Initializing ..."
cd ${curdir}
mkdocs init .

echo "Updating file ${curdir}/mkdocs.yml ..."
cat > ${curdir}/mkdocs.yml <<EOL
site_name: Project Documents

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: 'cloud'

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\ue157"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

EOL
fi

echo "Serving mkdocs from current directory"
mkdocs serve
